novel/urls.py
from django.conf.urls import url
from .views import *

app_name="novel"

urlpatterns = [
    url(r'^novel-list/$', novel_list,name='novel-list'),
    url(r'^novel-create/$', novel_create,name='novel-create'),

    url(r'^Haberler/$', haberler,name='haberler'),
    url(r'^Haber-create/$', haber_create, name='haber-create'),
    url(r'^(?P<id>\d+)/haberler/$', haberler_detail, name='haberler-detail'),

    url(r'^chapter-create/$', chapter_create, name='chapter-create'),

    url(r'^(?P<slug>[\w-]+)/Novel_Detayı/$', chapter_detail, name='chapter_detail'),
    url(r'^(?P<slug>[\w-]+)/$', novel_detail, name='novel-detail'),

    url(r'^(?P<id>\d+)/delete/$', comment_delete, name='commentdelete'),
    url(r'^(?P<id>\d+)/yorum-sil/$', ncomment_delete, name='ncommentdelete'),


]

novelstr/urls.py
from django.contrib import admin
from django.urls import path
from home.views import home_view
from ileişim.views import iletisim
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^novel/', include('novel.urls'),),
    url(r'^$', home_view, name='home'),
    url(r'^iletişim', iletisim, name='iletişim'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/post/chapter_detail.html
{% extends 'base.html' %}

    {% block title %}
    {{ chapter.chapter_name }} - {{ block.super }}
    {% endblock %}

    {% block body %}


<div class="">
  <div class="row row-grid justify-content-center" style="width:880px;margin:auto;">
    <div class="" style="width:880px;margin-top:20px;">
      <div class="info" style="padding-top:10px;max-width:880px;">
        <h1 class="text-white" style="margin-bottom:0px;">{{ chapter.novel|safe|linebreaks }}</h1>
        <hr class="line-info" style="width:90%;">
        <h4 class="info-title" style="margin-bottom:0px;">Bölüm {{ chapter.chapter_number}} / {{ chapter.chapter_name }}</h4>
        <hr class="line-info" style="width:80%;">
        <h4 class="info-title" style="margin-bottom:0px;">Çevirmen: {{ chapter.cevirmen }} & Redaktör: {{ chapter.redaktor }} </h4>
        <hr class="line-info" style="width:75%;">
        <div class="text-whit emb-3 " style="font-size:16px;">
          {{ chapter.chapter_content|safe|linebreaks }}
        </div>
      </div>
    </div>
  </div>
</div>


<div class="row row-grid justify-content-center" style="width:880px;margin:auto;">
  <div class="" style="width:880px;float:left;max-height:400px;margin-top:20px;">
    <div class="info" style="padding-top:10px;max-width:880px;">
      <div class="icon icon-primary">
        <i class="tim-icons icon-email-85"></i>
      </div>
      <h4 class="info-title">Yorum Yap</h4>
      <hr class="line-primary">
      {% include 'post/comments.html' %}
    </div>
  </div>
</div>

<div class="row row-grid justify-content-center" style="width:880px;margin:auto;">
      <div class="" style="width:880px;float:left;">
        <div class="info" style="padding-top:10px;max-width:880px;">
          <div class="icon icon-warning">
            <i class="tim-icons icon-chat-33"></i>
          </div>
          <h4 class="info-title">Tüm Yorumlar</h4>
          <hr class="line-warning" style="width:100%;">
          {% for comments in chapter.chaptercomment.all %}
            <div class="caption thumbnail" style="">
              <h5 style="color:#afabab; font-size:16px;"><strong>{{ comments.cc_name }} | </strong><small>{{ comments.cc_created_date }}</small></h5>
              <p style="color:#afabab;font-size:16px;">{{ comments.cc_content|linebreaks }}</p>
              {% if request.user.is_authenticated %}
                <a href="{{ comments.get_delete_url }}" class="btn btn-primary" role="button" data-toggle="">Sil</a>
              {% endif %}
            </div>
            <hr class="line-warning" style="width:100%;">
          {% endfor %}
        </div>
      </div>
    </div>

{% endblock %}

templates/post/comments.html
{% load crispy_forms_tags %}

<form class="form" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Yorum Gönder">
</form>

templates/post/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

    {% block body %}

        <div class="container">
            <div class="row">
                <div class="" style="margin:auto; width:800px;">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h1>Form</h1>
                        {{ form|crispy }}
                        {{ form.media}}
                        <input class="btn btn-default" type="submit" value="Gönder">
                    </form>
                </div>
            </div>
        </div>

    {% endblock %}

templates/post/detail.html
{% extends 'base.html' %}

    {% block title %}
    {{ novels.title }} - {{ block.super }}
    {% endblock %}

    {% block body %}

    <div class="wrapper" style="margin-top:50px;">
      <div class="page-header">
        <div class="container align-items-center">
          <div class="row">
            <div class="col-lg-6 col-md-6">
              <h1 class="profile-title text-left">{{ novels.title }}</h1>

                <!-- Nav tabs -->
                <div class="card" style="height:580px;">
                  <div class="card-header">
                    <ul class="nav nav-tabs nav-tabs-primary" role="tablist">
                      <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#link1" role="tablist">
                          <i class="tim-icons icon-spaceship"></i> Konusu
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#link2" role="tablist">
                          <i class="tim-icons icon-settings-gear-63"></i> Bölümler
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#link3" role="tablist">
                          <i class="tim-icons icon-bag-16"></i> Yorumlar
                        </a>
                      </li>
                    </ul>
                  </div>
                  <div class="card-body">
                    <!-- Tab panes -->
                    <div class="tab-content tab-space">
                      <div class="tab-pane active" id="link1" style="width:100%;height:450px; overflow-x:hidden;">
                        <p>{{ novels.content|safe|linebreaks }}</p>
                      </div>
                      <div class="tab-pane" id="link2">
                        {% if not chapter %}
                          <div class="" style="width:100%;">
                            <div class="caption thumbnail" style="width:100%;background-color:#984545">
                                <h5><strong style="color:white;"><center style="padding-top: 3px;padding-bottom: 3px;">
                                  Bu Novele ait bölüm bulunmamaktadır</center></strong></h5>
                            </div>
                          </div>
                        {% endif %}

                        <div class="" style="width:100%;height:450px; overflow-x:hidden;">
                        {% for chapter in chapter %}
                            <div class="" style="width:100%; margin:5px;">
                                <h5 style="color:#afabab;"><strong><a href="{{chapter.get_absolute_url}}">{{ chapter.chapter_number }}.Bölüm </a>|</strong> {{ chapter.chapter_name|truncatechars:25 }}   <small style="margin-left: 3px;">{{ chapter.created_date|timesince }} önce</small></h5>
                            </div>
                        {% endfor %}

                        </div>
                      </div>
                      <div class="tab-pane" id="link3" style="width:100%;height:450px; overflow-x:hidden;">
                          <hr class="line-primary">
                        {% for comments in novels.novelcomment.all %}
                          <div class="caption thumbnail" style="">
                            <h5 style="color:#afabab; font-size:16px;"><strong>{{ comments.nc_name }} | </strong><small>{{ comments.nc_created_date }}</small></h5>
                            <p style="color:#afabab;font-size:16px;">{{ comments.nc_content|linebreaks }}</p>
                            {% if request.user.is_authenticated %}
                              <a href="{{ comments.get_delete_url }}" class="btn btn-primary" role="button" data-toggle="">Sil</a>
                            {% endif %}
                          </div>
                          <hr class="line-primary">
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>


            </div>
            <div class="col-lg-4 col-md-6 ml-auto mr-auto">
              <div class="card card-coin card-plain">
                <div class="card-header" style="margin-top:5px;">
                  {% if novels.img %}
                      <img src="{{ novels.img.url }}" class="img-center img-fluid rounded shadow" alt="{{ novel.title }}">
                  {% endif %}
                  <h4 class="title"> {{ novels.auth }}</h4>
                </div>
                <div class="card-body">
                  <ul class="nav nav-tabs nav-tabs-primary justify-content-center">
                    <li class="nav-item">
                      <a class="nav-link active" data-toggle="tab" href="#linka">
                        Genel Bilgiler
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#linkb">
                        Diğer Adlar
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#linkc">
                        Novel Türü
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#linkd">
                        Novel Etiketi
                      </a>
                    </li>
                  </ul>
                  <div class="tab-content tab-subcategories">
                    <div class="tab-pane active" id="linka">
                      <div class="table-responsive" style="width:100%;height:100px; overflow-x:hidden;">
                        <div class="" style="width:100%;height:100px;">
                        <table class="table tablesorter " id="plain-table">
                          <thead class=" text-primary">

                          </thead>
                          <tbody>
                            <tr>
                              <td>
                                Uploader: {{ novels.user }}
                              </td>
                            </tr>
                            <tr>
                              <td>
                                Novel Tipi: {{ novels.type }}
                              </td>
                            </tr>
                            <tr>
                              <td>
                                Çıkış Yılı: {{ novels.year }}
                              </td>
                            </tr>
                            <tr>
                              <td>
                                Orjinal Dil:{{ novels.league }}
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </div>


                      </div>
                    </div>
                    <div class="tab-pane" id="linkb">
                      <div class="row" style="width:100%;height:100px; overflow-x:hidden;">

                        <p>{{ novels.name}}</p>

                      </div>
                    </div>
                    <div class="tab-pane" id="linkc">
                      <div class="row" style="width:100%;height:100px; overflow-x:hidden;">

                        <p>{{ novels.genre }}</p>

                      </div>
                    </div>
                    <div class="tab-pane" id="linkd">
                      <div class="row" style="width:100%;height:100px; overflow-x:hidden;">

                        <p>{{ novels.tags }}</p>

                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


<div class="container"  style="width:100%; margin:50px;">
  <div class="row">
        <div class="" style="width:100%; margin:10px;">
            <div class="Form-group" style="width:90%; margin:auto;">
              <div class="icon icon-primary">
                <i class="tim-icons icon-email-85"></i>
              </div>
              <h4 class="info-title">Yorum Yap</h4>
              <hr class="line-primary">
                {% include 'post/comments.html' %}
            </div>
        </div>
    </div>
  </div>










    {% endblock %}

templates/post/fotter.html
<div class="wrapper">
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h1 class="title">NovelsTr•</h1>
      </div>
      <div class="col-md-3">
        <p class="text-success">Bu site Djano ile yazılmıştır. Backend kodlaması Ömer Ali Çaylar tarafından yapılmıştır.Bu sitede bulunan seriler fan yapımı olduğundan telif haklarını ihlal eden bir seri bulunursa omeralicaylar5@gmail.com adresine mesaj atınız.</p>
        <p class="text-success" style="color:#337ab7;"><span>©  </span><span class="copyright-year">2020</span><span> </span><span>ArazNovel</span><span>. </span></p>
      </div>
      <div class="col-md-3">
        <div class="text-success"><a class="brand" href="{##}"><img class="brand-logo-light" src="images/agency/logo-inverse-140x37.png" alt="" width="140" height="37" srcset="images/agency/logo-retina-inverse-280x74.png 2x"></a>
          <dt>Site:</dt>
          <dd>https://www.araznovel.com</dd>
            <br>
            <dt>email:</dt>
          <dd><a href="mailto:#">omeralicaylar5@gmail.com</a></dd>
        </div>
      </div>
      <div class="col-md-3">
        <h4 class="title"><i class="tim-icons icon-spaceship"></i> Bu siteye sponsor ol</h4>

      </div>
    </div>
  </div>
</footer>
</div>

templates/post/haberler.html
{% extends 'base.html' %}

{% block title %}
Haberler - {{ block.super }}
{% endblock %}

{% block body %}

<div class="container">
  <div class="row">
    <h4 style="color:#afabab;"><strong>Haber Güncellemeleri</strong></h4>
    <hr class="line-info" style="width:100%">
    {% for haberlers in haber %}
    <div class="col-md-10 ml-auto col-xl-6 mr-auto" >
      <div class="card">
        <div class="card-body">
          {% if haberlers.h_img %}
          <div style="float:left; width:90px; margin-right:10px;">

                <img src="{{ haberlers.h_img.url }}" alt="{{ haberlers.h_title}}"class="img-fluid rounded shadow-lg" style="width: 90px;height:130px;;float:left;" />

          </div>
          {% endif %}
          <div class="" style="">
            <p><a href="{{ haberlers.get_absolute_url }}" class="text-warning" style="font-size:16px;">{{ haberlers.h_title}}</a> |{{ haberlers.h_created_date|timesince }} önce önce</p>
            <p><strong>Yazar: {{ haberlers.h_user }}</strong></p>
            <p>{{ haberlers.h_content|safe|linebreaks|truncatechars:240}}</p>
            <a href="{{ haberlers.get_absolute_url }}"class="btn btn-info btn-round btn-sm" style="width:90px;margin-top:5px;" ><i style="" class="tim-icons icon-gift-2"></i>Oku</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <ul class="pagination">
    <li class="page-item" style="padding:3px;">

        {% if haber.has_previous %}
            <a class="tim-icons icon-double-left" href="?page=1"></a>
            <a class="tim-icons icon-minimal-left" href="?page={{ haber.previous_page_number }}"></a>
        {% endif %}

    </li>

    <li class="page-item active">
      <a class="page-link" href="#link">{{ haber.number }}</a>
    </li>

    <li class="page-item" style="padding:3px;">

        {% if haber.has_next %}
            <a class="tim-icons icon-minimal-right" href="?page={{ haber.next_page_number }}"></a>
            <a class="tim-icons icon-double-right" href="?page={{ haber.paginator.num_pages }}"></a>
        {% endif %}

    </li>
  </ul>
</div>

{% endblock %}

templates/post/haberler_detail.html
{% extends 'base.html' %}

    {% block title %}
    {{ haber.h_title }} - {{ block.super }}
    {% endblock %}

    {% block body %}

<div class="container">
  <div class="row">
      <div class="" style="">
        {% if haber.h_img %}
            <img style="border-radius:10px;width:1170px;height:300px; margin:10px;"src="{{ haber.h_img.url }}" class="img-responsave " alt="{{ haber.h_title }}">
        {% endif %}
      </div>

        <div class="" style="margin:10px;height:50px;width:950px;">
            <div class="" style="">
             <h3><a style="color:#afabab;" href="{{ haber.get_absolute_url }}">{{ haber.h_title }}</a> <small>{{ haber.h_created_date|timesince }} önce</small></h3>
         </div>

        </div>

      <div class=""style="color:#afabab;margin:10px">
        <p>{{ haber.h_content|safe|linebreaks }}</p>
      </div>

      <div class="row row-grid justify-content-center" style="width:880px;margin:auto;">
        <div class="" style="width:880px;float:left;max-height:400px;margin-top:20px;">
          <div class="info" style="padding-top:10px;max-width:880px;">
            <div class="icon icon-primary">
              <i class="tim-icons icon-email-85"></i>
            </div>
            <h4 class="info-title">Yorum Yap</h4>
            <hr class="line-primary">
            {% include 'post/comments.html' %}
          </div>
        </div>
      </div>

      <div class="row row-grid justify-content-center" style="width:880px;margin:auto;">
            <div class="" style="width:880px;float:left;">
              <div class="info" style="padding-top:10px;max-width:880px;">
                <div class="icon icon-warning">
                  <i class="tim-icons icon-chat-33"></i>
                </div>
                <h4 class="info-title">Tüm Yorumlar</h4>
                <hr class="line-warning" style="width:100%;">
                {% for comments in haber.haberlercomment.all %}
                  <div class="caption thumbnail" style="">
                    <h5 style="color:#afabab; font-size:16px;"><strong>{{ comments.hc_name }} |</strong><small>{{ comments.hc_created_date }}</small></h5>
                    <p style="color:#afabab;font-size:16px;">{{ comments.hc_content|linebreaks }}</p>
                    {% if request.user.is_authenticated %}
                      <a href="{{ comments.get_delete_url }}" class="btn btn-success" role="button" data-toggle="">Sil</a>
                    {% endif %}
                  </div>
                  <hr class="line-warning" style="width:100%;">
                {% endfor %}
              </div>
            </div>
          </div>


    </div>
  </div>
{% endblock %}

templates/post/header.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg fixed-top navbar-transparent bg-info " color-on-scroll="100">
  <div class="container">
    <div class="navbar-translate">
      <a class="navbar-brand" href="{% url 'home' %}" rel="tooltip" title="" data-placement="bottom" target="">
        <span>Novels Tr</span> v1.0.0
      </a>
      <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-bar bar1"></span>
        <span class="navbar-toggler-bar bar2"></span>
        <span class="navbar-toggler-bar bar3"></span>
        <span class="navbar-toggler-bar bar4"></span>
        <span class="navbar-toggler-bar bar5"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="example-navbar-primary">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">
            <i class="tim-icons icon-bank"></i>Anasayfa
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'novel:novel-list' %}">
            <i class="tim-icons icon-book-bookmark"></i> Novel List
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'novel:haberler' %}">
            <i class="tim-icons icon-paper"></i> Haberler
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'iletişim' %}">
            <i class="tim-icons icon-send"></i> İletişim
          </a>
        </li>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown">
            <i class="tim-icons icon-zoom-split" aria-hidden="true"></i>Novel Ara
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-header text-warning">Arama Yap</a>
            <form class="navbar-form ml-auto" role="search"style="width:310px;" method="GET" action="">
                <div class="form-group has-regular nav-item ">
                    <input class="form-control"  style="width:300px;margin:auto;" type="text" name="q" placeholder="Ad,Tür, Etiket vb. Novel Ara " value="{{ request.GET.q }}" >

                </div>
                  <button type="submit" style="width:300px;margin-left:5px;" class="btn btn-info btn-round">
                    <i style="margin:auto;"class="tim-icons icon-compass-05"></i>Ara
                  </button>
            </form>
          </div>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown">
            <i class="tim-icons icon-single-02" aria-hidden="true"></i>{{ request.user}}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-header text-warning">Ayarlar</a>
            <a class="dropdown-item text-info" href="{% url 'novel:novel-create' %}"">Novel Ekle</a>
            <a class="dropdown-item text-info" href="{% url 'novel:chapter-create' %}">Bölüm Ekle</a>
            <a class="dropdown-item text-info" href="{% url 'novel:haber-create' %}">Haber Ekle</a>
          </div>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar -->

templates/post/index.html
{% extends 'base.html' %}

{% block title %}
Novel List - {{ block.super }}
{% endblock %}

{% block body %}

<div class="container">
  <div class="row">
    <h4 style="color:#afabab;"><strong>Novel Listesi</strong></h4>
    <hr class="line-info" style="width:100%">
    {% for novels in novels %}
    <div class="col-md-10 ml-auto col-xl-6 mr-auto" >
      <div class="card">
        <div class="card-body">
          <div style="float:left; width:90px;">
            {% if novels.img %}
                <img src="{{ novels.img.url }}" alt="{{novels.title}}"class="img-fluid rounded shadow-lg" style="width: 90px;height:130px;;float:left;" />
            {% endif %}
            {% if not novels.img %}
              <img src="/media/none2.jpg" alt="Novels Tr" class="img-fluid rounded shadow-lg" style="width: 90px;height:130px;"/>
            {% endif %}
            <a href="{{ novels.get_absolute_url }}"class="btn btn-info btn-round btn-sm" style="width:90px;margin-top:5px;" ><i style="" class="tim-icons icon-gift-2"></i>Oku</a>
          </div>

          <div class="" style="margin-left:100px;">
            <p><a href="{{ novels.get_absolute_url }}" class="text-warning" style="font-size:16px;">{{ novels.title }}</a> | {{ novels.publishing_date|timesince }} önce</p>
            <p><strong>Uploader: {{ novels.user }}</strong></p>
            <p>{{ novels.content|safe|linebreaks|truncatechars:240}}</p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <ul class="pagination">
    <li class="page-item" style="padding:3px;">

        {% if novels.has_previous %}
            <a class="tim-icons icon-double-left" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"></a>
            <a class="tim-icons icon-minimal-left" href="?page={{ novels.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"></a>
        {% endif %}

    </li>

    <li class="page-item active">
      <a class="page-link" href="#link">{{ novels.number }}</a>
    </li>

    <li class="page-item" style="padding:3px;">

        {% if novels.has_next %}
            <a class="tim-icons icon-minimal-right" href="?page={{ novels.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"></a>
            <a class="tim-icons icon-double-right" href="?page={{ novels.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"></a>
        {% endif %}

    </li>
  </ul>
</div>
{% endblock %}